DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_CONTACT_LIST');
INSERT INTO `opcodes` VALUES ('CMSG_CONTACT_LIST', 0x4534, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_CONTACT_LIST');
INSERT INTO `opcodes` VALUES ('SMSG_CONTACT_LIST', 0x6017, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_ADD_FRIEND');
INSERT INTO `opcodes` VALUES ('CMSG_ADD_FRIEND', 0x6527, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_ADD_IGNORE');
INSERT INTO `opcodes` VALUES ('CMSG_ADD_IGNORE', 0x4726, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_DEL_FRIEND');
INSERT INTO `opcodes` VALUES ('CMSG_DEL_FRIEND', 0x6A15, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_DEL_IGNORE');
INSERT INTO `opcodes` VALUES ('CMSG_DEL_IGNORE', 0x6D26, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_FRIEND_STATUS');
INSERT INTO `opcodes` VALUES ('SMSG_FRIEND_STATUS', 0x0717, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_SET_CONTACT_NOTES');
INSERT INTO `opcodes` VALUES ('CMSG_SET_CONTACT_NOTES', 0x6135, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_WHO');
INSERT INTO `opcodes` VALUES ('CMSG_WHO', 0x6C15, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_WHO');
INSERT INTO `opcodes` VALUES ('SMSG_WHO', 0x6907, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_WHOIS');
INSERT INTO `opcodes` VALUES ('CMSG_WHOIS', 0x6B05, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_GROUP_INVITE');
INSERT INTO `opcodes` VALUES ('CMSG_GROUP_INVITE', 0x513, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_PLAYED_TIME');
INSERT INTO `opcodes` VALUES ('SMSG_PLAYED_TIME', 0x6037, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_PARTY_COMMAND_RESULT');
INSERT INTO `opcodes` VALUES ('SMSG_PARTY_COMMAND_RESULT', 0x6E07, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_GROUP_LIST');
INSERT INTO `opcodes` VALUES ('SMSG_GROUP_LIST', 0x4C24, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_GROUP_SET_LEADER');
INSERT INTO `opcodes` VALUES ('CMSG_GROUP_SET_LEADER', 0x4C17, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_GROUP_SET_LEADER');
INSERT INTO `opcodes` VALUES ('SMSG_GROUP_SET_LEADER', 0x0526, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_WORLD_STATE_UI_TIMER_UPDATE');
INSERT INTO `opcodes` VALUES ('CMSG_WORLD_STATE_UI_TIMER_UPDATE', 0x4605, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_WORLD_STATE_UI_TIMER_UPDATE');
INSERT INTO `opcodes` VALUES ('SMSG_WORLD_STATE_UI_TIMER_UPDATE', 0x4A14, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_FLIGHT_SPLINE_SYNC');
INSERT INTO `opcodes` VALUES ('SMSG_FLIGHT_SPLINE_SYNC', 0x0924, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_EMOTE');
INSERT INTO `opcodes` VALUES ('SMSG_EMOTE', 0x0A34, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_EMOTE');
INSERT INTO `opcodes` VALUES ('CMSG_EMOTE', 0x4C26, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_TEXT_EMOTE');
INSERT INTO `opcodes` VALUES ('CMSG_TEXT_EMOTE', 0x2E24, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_GUILD_EVENT');
INSERT INTO `opcodes` VALUES ('SMSG_GUILD_EVENT', 0x0705, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_CORPSE_RECLAIM_DELAY');
INSERT INTO `opcodes` VALUES ('SMSG_CORPSE_RECLAIM_DELAY', 0x0D34, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_ALL_ACHIEVEMENT_DATA');
INSERT INTO `opcodes` VALUES ('SMSG_ALL_ACHIEVEMENT_DATA', 0x58B1, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_REMOVED_SPELL');
INSERT INTO `opcodes` VALUES ('SMSG_REMOVED_SPELL', 0x4804, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_SET_ACTION_BUTTON');
INSERT INTO `opcodes` VALUES ('CMSG_SET_ACTION_BUTTON', 0x6F06, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_QUERY_TIME_RESPONSE');
INSERT INTO `opcodes` VALUES ('SMSG_QUERY_TIME_RESPONSE', 0x2124, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_CAST_FAILED');
INSERT INTO `opcodes` VALUES ('SMSG_CAST_FAILED', 0x4D16, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_SET_PROFICIENCY');
INSERT INTO `opcodes` VALUES ('SMSG_SET_PROFICIENCY', 0x6207, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_CANCEL_CAST');
INSERT INTO `opcodes` VALUES ('CMSG_CANCEL_CAST', 0x0115, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_SPELL_COOLDOWN');
INSERT INTO `opcodes` VALUES ('SMSG_SPELL_COOLDOWN', 0x4B16, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_WHOIS');
INSERT INTO `opcodes` VALUES ('SMSG_WHOIS', 0x6917, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_LOGOUT_CANCEL');
INSERT INTO `opcodes` VALUES ('SMSG_LOGOUT_CANCEL', 25876, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_FORCE_MOVE_ROOT');
INSERT INTO `opcodes` VALUES ('SMSG_FORCE_MOVE_ROOT', 32160, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_FORCE_MOVE_ROOT_ACK');
INSERT INTO `opcodes` VALUES ('CMSG_FORCE_MOVE_ROOT_ACK', 28702, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_FORCE_MOVE_UNROOT');
INSERT INTO `opcodes` VALUES ('SMSG_FORCE_MOVE_UNROOT', 32180, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_FORCE_MOVE_UNROOT_ACK');
INSERT INTO `opcodes` VALUES ('CMSG_FORCE_MOVE_UNROOT_ACK', 30728, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_LEVELUP_INFO');
INSERT INTO `opcodes` VALUES ('SMSG_LEVELUP_INFO', 1077, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_LOG_DISCONNECT');
INSERT INTO `opcodes` VALUES ('CMSG_LOG_DISCONNECT', 0x446D, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_STANDSTATE_UPDATE');
INSERT INTO `opcodes` VALUES ('SMSG_STANDSTATE_UPDATE', 0x6F04, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_PLAY_SPELL_VISUAL');
INSERT INTO `opcodes` VALUES ('SMSG_PLAY_SPELL_VISUAL', 0x55A5, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_SET_CURRENCY_WEEK_LIMIT');
INSERT INTO `opcodes` VALUES ('SMSG_SET_CURRENCY_WEEK_LIMIT', 0x70A7, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_SET_CURRENCY');
INSERT INTO `opcodes` VALUES ('SMSG_SET_CURRENCY', 22960, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_SETUP_CURRENCY');
INSERT INTO `opcodes` VALUES ('SMSG_SETUP_CURRENCY', 5541, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_UPDATE_WORLD_STATE');
INSERT INTO `opcodes` VALUES ('SMSG_UPDATE_WORLD_STATE', 0x4816, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_INIT_WORLD_STATES');
INSERT INTO `opcodes` VALUES ('SMSG_INIT_WORLD_STATES', 0x4C15, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_PLAY_SOUND');
INSERT INTO `opcodes` VALUES ('SMSG_PLAY_SOUND', 0x2134, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_INVENTORY_CHANGE_FAILURE');
INSERT INTO `opcodes` VALUES ('SMSG_INVENTORY_CHANGE_FAILURE', 0x2236, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_SELL_ITEM');
INSERT INTO `opcodes` VALUES ('SMSG_SELL_ITEM', 0x6105, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_SELL_ITEM');
INSERT INTO `opcodes` VALUES ('CMSG_SELL_ITEM', 0x4E15, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_BUY_ITEM');
INSERT INTO `opcodes` VALUES ('CMSG_BUY_ITEM', 0x0736, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_BUY_ITEM');
INSERT INTO `opcodes` VALUES ('SMSG_BUY_ITEM', 0x0F26, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_CANCEL_TRADE');
INSERT INTO `opcodes` VALUES ('CMSG_CANCEL_TRADE', 0x731E, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_INITIATE_TRADE');
INSERT INTO `opcodes` VALUES ('CMSG_INITIATE_TRADE', 0x7916, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_USE_ITEM');
INSERT INTO `opcodes` VALUES ('CMSG_USE_ITEM', 0x2C06, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_GUILD_COMMAND_RESULT');
INSERT INTO `opcodes` VALUES ('SMSG_GUILD_COMMAND_RESULT', 0x2707, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_LOOT_MONEY');
INSERT INTO `opcodes` VALUES ('CMSG_LOOT_MONEY', 0x6227, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_LOOT_RELEASE');
INSERT INTO `opcodes` VALUES ('CMSG_LOOT_RELEASE', 0x200, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_LOOT_MONEY_NOTIFY');
INSERT INTO `opcodes` VALUES ('SMSG_LOOT_MONEY_NOTIFY', 0x2836, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_SPELL_FAILED_OTHER');
INSERT INTO `opcodes` VALUES ('SMSG_SPELL_FAILED_OTHER', 0x4535, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_QUERY_INSPECT_ACHIEVEMENTS');
INSERT INTO `opcodes` VALUES ('CMSG_QUERY_INSPECT_ACHIEVEMENTS', 0x4D27, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_RESPOND_INSPECT_ACHIEVEMENTS');
INSERT INTO `opcodes` VALUES ('SMSG_RESPOND_INSPECT_ACHIEVEMENTS', 0x15B0, '15595', '15595');